### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by dskuratovich** [Needlide/Astronews.UI#3]
Hello @Needlide, is the project still alive? I would like to suggest help if needed

**Comment by Needlide** [comment]
Hello. I'd say that yes, it's alive. Didn't have much time (and knowledge) to continue the work on the project, but from December I plan to work on it more actively, especially if there are people interested in it.
Any help is really appreciated. If you're interested, I was thinking for some time about implementing state management using `ngRX`, loading spinner for the initial page load, and  `About` page, where I wanted to put the info about the project itself and explain how to use the search bar. There's more, of course, but other features would be better to implement after state management.
Thank you for your interest, and thanks for the first issue!

**Comment by dskuratovich** [comment]
Hi @Needlide, thanks for such a fast answer 😄 Yes I'd like to help and would love to participate in the project development activities!

First of all, I will fork the repo and see how I can help you. 
You can directly contact me in Discord, for example **dskuratovich**

**Comment by dskuratovich** [comment]
Closing the issue
